# Generated by Django 4.2.5 on 2025-07-06 17:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('done', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(default=datetime.date.today)),
                ('date_completed', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
