# Generated by Django 4.2.5 on 2025-07-07 07:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='date_completed',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 7, 7, 7, 23, 46, 428933, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
